### ISSUE TITLE
Ensure that examples don't have horrid display

### ISSUE THREAD

**Issue by pfps** [linkeddata/dokieli#16]
https://github.com/csarven/linked-research/blob/master/linked-sdmx-data.pdf
looks horrid.  Two floats overflow their boundaries.  Several displays use low resolution graphics.  One colum is mostly empty.

Anyone looking at this example would conclude that the system is fatally flawed.

**Comment by csarven** [comment]
Indeed the ACM style needs to be updated to handle overflows from tables. This issue was mentioned at issue dokieli/themes#8 .

Background: Actually, when the ACM style was first created it was okay. The problem started when I updated the HTML (with more columns for the table) without going back and fixing the desired rendering. As the canonical version of the paper was at http://csarven.ca/linked-sdmx-data , I didn't have the energy for it. An outdated _snapshot_ of that paper is published at http://iospress.metapress.com/content/q155485487082hj2/ (which was unfortunately submitted in LaTeX).
